var annotated_dup =
[
    [ "bWidgets", "namespacebWidgets.html", [
      [ "bwScreenGraph", "namespacebWidgets_1_1bwScreenGraph.html", [
        [ "Builder", "classbWidgets_1_1bwScreenGraph_1_1Builder.html", "classbWidgets_1_1bwScreenGraph_1_1Builder" ],
        [ "ContainerNode", "classbWidgets_1_1bwScreenGraph_1_1ContainerNode.html", "classbWidgets_1_1bwScreenGraph_1_1ContainerNode" ],
        [ "Drawer", "classbWidgets_1_1bwScreenGraph_1_1Drawer.html", "classbWidgets_1_1bwScreenGraph_1_1Drawer" ],
        [ "EventHandler", "classbWidgets_1_1bwScreenGraph_1_1EventHandler.html", "classbWidgets_1_1bwScreenGraph_1_1EventHandler" ],
        [ "LayoutNode", "classbWidgets_1_1bwScreenGraph_1_1LayoutNode.html", "classbWidgets_1_1bwScreenGraph_1_1LayoutNode" ],
        [ "Node", "classbWidgets_1_1bwScreenGraph_1_1Node.html", "classbWidgets_1_1bwScreenGraph_1_1Node" ],
        [ "PreOrderIterator", "classbWidgets_1_1bwScreenGraph_1_1PreOrderIterator.html", "classbWidgets_1_1bwScreenGraph_1_1PreOrderIterator" ],
        [ "ScreenGraph", "classbWidgets_1_1bwScreenGraph_1_1ScreenGraph.html", "classbWidgets_1_1bwScreenGraph_1_1ScreenGraph" ],
        [ "WidgetNode", "classbWidgets_1_1bwScreenGraph_1_1WidgetNode.html", "classbWidgets_1_1bwScreenGraph_1_1WidgetNode" ]
      ] ],
      [ "bwAbstractButton", "classbWidgets_1_1bwAbstractButton.html", "classbWidgets_1_1bwAbstractButton" ],
      [ "bwAbstractButtonHandler", "classbWidgets_1_1bwAbstractButtonHandler.html", "classbWidgets_1_1bwAbstractButtonHandler" ],
      [ "bwCheckbox", "classbWidgets_1_1bwCheckbox.html", "classbWidgets_1_1bwCheckbox" ],
      [ "bwCheckboxHandler", "classbWidgets_1_1bwCheckboxHandler.html", "classbWidgets_1_1bwCheckboxHandler" ],
      [ "bwColor", "classbWidgets_1_1bwColor.html", "classbWidgets_1_1bwColor" ],
      [ "bwContainerWidget", "classbWidgets_1_1bwContainerWidget.html", "classbWidgets_1_1bwContainerWidget" ],
      [ "bwContext", "structbWidgets_1_1bwContext.html", "structbWidgets_1_1bwContext" ],
      [ "bwEvent", "classbWidgets_1_1bwEvent.html", "classbWidgets_1_1bwEvent" ],
      [ "bwEventDispatcher", "classbWidgets_1_1bwEventDispatcher.html", "classbWidgets_1_1bwEventDispatcher" ],
      [ "bwFunctorInterface", "classbWidgets_1_1bwFunctorInterface.html", "classbWidgets_1_1bwFunctorInterface" ],
      [ "bwGradient", "classbWidgets_1_1bwGradient.html", "classbWidgets_1_1bwGradient" ],
      [ "bwIconInterface", "classbWidgets_1_1bwIconInterface.html", "classbWidgets_1_1bwIconInterface" ],
      [ "bwLabel", "classbWidgets_1_1bwLabel.html", "classbWidgets_1_1bwLabel" ],
      [ "bwLayoutInterface", "classbWidgets_1_1bwLayoutInterface.html", "classbWidgets_1_1bwLayoutInterface" ],
      [ "bwMouseButtonDragEvent", "classbWidgets_1_1bwMouseButtonDragEvent.html", "classbWidgets_1_1bwMouseButtonDragEvent" ],
      [ "bwMouseButtonEvent", "classbWidgets_1_1bwMouseButtonEvent.html", "classbWidgets_1_1bwMouseButtonEvent" ],
      [ "bwMouseWheelEvent", "classbWidgets_1_1bwMouseWheelEvent.html", "classbWidgets_1_1bwMouseWheelEvent" ],
      [ "bwNumberSlider", "classbWidgets_1_1bwNumberSlider.html", "classbWidgets_1_1bwNumberSlider" ],
      [ "bwNumberSliderHandler", "classbWidgets_1_1bwNumberSliderHandler.html", "classbWidgets_1_1bwNumberSliderHandler" ],
      [ "bwPaintEngine", "classbWidgets_1_1bwPaintEngine.html", "classbWidgets_1_1bwPaintEngine" ],
      [ "bwPainter", "classbWidgets_1_1bwPainter.html", "classbWidgets_1_1bwPainter" ],
      [ "bwPanel", "classbWidgets_1_1bwPanel.html", "classbWidgets_1_1bwPanel" ],
      [ "bwPanelHandler", "classbWidgets_1_1bwPanelHandler.html", "classbWidgets_1_1bwPanelHandler" ],
      [ "bwPoint", "classbWidgets_1_1bwPoint.html", "classbWidgets_1_1bwPoint" ],
      [ "bwPolygon", "classbWidgets_1_1bwPolygon.html", "classbWidgets_1_1bwPolygon" ],
      [ "bwPushButton", "classbWidgets_1_1bwPushButton.html", "classbWidgets_1_1bwPushButton" ],
      [ "bwRadioButton", "classbWidgets_1_1bwRadioButton.html", "classbWidgets_1_1bwRadioButton" ],
      [ "bwRadioButtonHandler", "classbWidgets_1_1bwRadioButtonHandler.html", "classbWidgets_1_1bwRadioButtonHandler" ],
      [ "bwRange", "classbWidgets_1_1bwRange.html", "classbWidgets_1_1bwRange" ],
      [ "bwRectangle", "classbWidgets_1_1bwRectangle.html", "classbWidgets_1_1bwRectangle" ],
      [ "bwScrollBar", "classbWidgets_1_1bwScrollBar.html", "classbWidgets_1_1bwScrollBar" ],
      [ "bwScrollBarHandler", "classbWidgets_1_1bwScrollBarHandler.html", "classbWidgets_1_1bwScrollBarHandler" ],
      [ "bwScrollView", "classbWidgets_1_1bwScrollView.html", "classbWidgets_1_1bwScrollView" ],
      [ "bwScrollViewHandler", "classbWidgets_1_1bwScrollViewHandler.html", "classbWidgets_1_1bwScrollViewHandler" ],
      [ "bwStyle", "classbWidgets_1_1bwStyle.html", "classbWidgets_1_1bwStyle" ],
      [ "bwStyleClassic", "classbWidgets_1_1bwStyleClassic.html", "classbWidgets_1_1bwStyleClassic" ],
      [ "bwStyleCSS", "classbWidgets_1_1bwStyleCSS.html", "classbWidgets_1_1bwStyleCSS" ],
      [ "bwStyleFlat", "classbWidgets_1_1bwStyleFlat.html", "classbWidgets_1_1bwStyleFlat" ],
      [ "bwStyleFlatDark", "classbWidgets_1_1bwStyleFlatDark.html", "classbWidgets_1_1bwStyleFlatDark" ],
      [ "bwStyleFlatLight", "classbWidgets_1_1bwStyleFlatLight.html", "classbWidgets_1_1bwStyleFlatLight" ],
      [ "bwStyleManager", "classbWidgets_1_1bwStyleManager.html", "classbWidgets_1_1bwStyleManager" ],
      [ "bwStyleProperties", "classbWidgets_1_1bwStyleProperties.html", "classbWidgets_1_1bwStyleProperties" ],
      [ "bwStyleProperty", "classbWidgets_1_1bwStyleProperty.html", "classbWidgets_1_1bwStyleProperty" ],
      [ "bwStylePropertyInternal", "classbWidgets_1_1bwStylePropertyInternal.html", "classbWidgets_1_1bwStylePropertyInternal" ],
      [ "bwTextBox", "classbWidgets_1_1bwTextBox.html", "classbWidgets_1_1bwTextBox" ],
      [ "bwTextBoxHandler", "classbWidgets_1_1bwTextBoxHandler.html", "classbWidgets_1_1bwTextBoxHandler" ],
      [ "bwWidget", "classbWidgets_1_1bwWidget.html", "classbWidgets_1_1bwWidget" ],
      [ "bwWidgetBaseStyle", "classbWidgets_1_1bwWidgetBaseStyle.html", "classbWidgets_1_1bwWidgetBaseStyle" ],
      [ "PolygonRoundboxCreator", "classbWidgets_1_1PolygonRoundboxCreator.html", "classbWidgets_1_1PolygonRoundboxCreator" ],
      [ "PropType", "structbWidgets_1_1PropType.html", null ],
      [ "PropType< bool >", "structbWidgets_1_1PropType_3_01bool_01_4.html", "structbWidgets_1_1PropType_3_01bool_01_4" ],
      [ "PropType< bwColor >", "structbWidgets_1_1PropType_3_01bwColor_01_4.html", "structbWidgets_1_1PropType_3_01bwColor_01_4" ],
      [ "PropType< float >", "structbWidgets_1_1PropType_3_01float_01_4.html", "structbWidgets_1_1PropType_3_01float_01_4" ],
      [ "PropType< int >", "structbWidgets_1_1PropType_3_01int_01_4.html", "structbWidgets_1_1PropType_3_01int_01_4" ]
    ] ]
];